#!/usr/bin/env python3

from __future__ import annotations

import sys
import json
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr
import rasterio

from backend.depth.depth_engine import run_geotiff


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[1]

EXPERIMENT_DIR = (
    PROJECT_ROOT
    / "data"
    / "dfc2019"
    / "experiments"
    / "dav2_baseline"
)

MANIFEST_PATH = EXPERIMENT_DIR / "manifest.csv"
METRICS_PATH = EXPERIMENT_DIR / "metrics.csv"
DEPTH_DIR = EXPERIMENT_DIR / "depth"

# Temporary directory used by the existing run_geotiff() implementation.
# Its generated files are copied/renamed into DEPTH_DIR below.
TMP_DIR = DEPTH_DIR / "_tmp"

DEPTH_DIR.mkdir(parents=True, exist_ok=True)
TMP_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def load_agl(path: Path) -> np.ndarray:
    """Load the first AGL band as float32."""
    with rasterio.open(path) as src:
        agl = src.read(1).astype(np.float32)

    return agl


def load_dav2(path: Path) -> np.ndarray:
    """Load saved DAv2 numpy prediction."""
    depth = np.load(path).astype(np.float32)

    if depth.ndim != 2:
        raise ValueError(
            f"Expected 2D DAv2 array, got shape {depth.shape}: {path}"
        )

    return depth


def calculate_correlations(
    depth: np.ndarray,
    agl: np.ndarray,
) -> tuple[float, float, int]:
    """
    Calculate Pearson and Spearman correlation using only finite,
    pixel-aligned values.
    """

    if depth.shape != agl.shape:
        raise ValueError(
            f"Shape mismatch: DAv2={depth.shape}, AGL={agl.shape}"
        )

    valid = np.isfinite(depth) & np.isfinite(agl)

    depth_valid = depth[valid].astype(np.float64)
    agl_valid = agl[valid].astype(np.float64)

    if len(depth_valid) < 2:
        raise ValueError("Not enough valid pixels for correlation.")

    # Constant arrays make correlation undefined.
    if np.std(depth_valid) == 0 or np.std(agl_valid) == 0:
        return np.nan, np.nan, int(len(depth_valid))

    pearson = float(pearsonr(depth_valid, agl_valid).statistic)
    spearman = float(spearmanr(depth_valid, agl_valid).statistic)

    return pearson, spearman, int(len(depth_valid))


def safe_float(value) -> float:
    """Convert numpy/scalar values into regular JSON/CSV-friendly floats."""
    if value is None:
        return np.nan

    value = float(value)

    return value if np.isfinite(value) else np.nan


def find_generated_depth(result: dict) -> Path:
    """
    Find the .npy output generated by the existing run_geotiff() result.
    """

    npy_path = result.get("depth_npy")

    if not npy_path:
        raise RuntimeError(
            "run_geotiff() did not return 'depth_npy'. "
            f"Result was: {result}"
        )

    path = Path(npy_path)

    if not path.is_absolute():
        path = Path.cwd() / path

    if not path.exists():
        raise FileNotFoundError(
            f"DAv2 output reported by run_geotiff() does not exist: {path}"
        )

    return path


# ---------------------------------------------------------------------
# Main evaluation
# ---------------------------------------------------------------------

def main() -> None:
    if not MANIFEST_PATH.exists():
        raise FileNotFoundError(
            f"Manifest not found: {MANIFEST_PATH}"
        )

    manifest = pd.read_csv(MANIFEST_PATH)

    required_columns = {
        "tile_id",
        "city",
        "rgb_path",
        "agl_path",
    }

    missing_columns = required_columns - set(manifest.columns)

    if missing_columns:
        raise ValueError(
            f"Manifest is missing columns: {sorted(missing_columns)}"
        )

    # Load previous metrics so interrupted runs can resume.
    if METRICS_PATH.exists():
        existing_metrics = pd.read_csv(METRICS_PATH)

        completed = set(existing_metrics["tile_id"].astype(str))
        results = existing_metrics.to_dict("records")

        print(
            f"Found existing metrics.csv with {len(completed)} completed tile(s)."
        )
    else:
        completed = set()
        results = []

    print(f"Benchmark tiles in manifest: {len(manifest)}")
    print(f"Already completed: {len(completed)}")
    print()

    for index, row in manifest.iterrows():
        tile_id = str(row["tile_id"])
        city = str(row["city"])

        rgb_path = PROJECT_ROOT / str(row["rgb_path"])
        agl_path = PROJECT_ROOT / str(row["agl_path"])

        final_depth_path = DEPTH_DIR / f"{tile_id}_depth.npy"

        print(
            f"[{index + 1}/{len(manifest)}] "
            f"{tile_id} ({city})"
        )

        # -------------------------------------------------------------
        # Reuse already-generated DAv2 output when possible.
        # -------------------------------------------------------------

        if final_depth_path.exists():
            print("  DAv2 output already exists — reusing it.")
            depth_path = final_depth_path

            runtime_sec = np.nan

        else:
            print(f"  RGB: {rgb_path}")

            if not rgb_path.exists():
                print("  ERROR: RGB file does not exist. Skipping.")
                continue

            print("  Running DAv2...")

            start = time.perf_counter()

            result = run_geotiff(
                rgb_path,
                TMP_DIR,
            )

            runtime_sec = time.perf_counter() - start

            generated_path = find_generated_depth(result)

            # Move/copy into canonical experiment location.
            depth = np.load(generated_path)

            np.save(final_depth_path, depth)

            depth_path = final_depth_path

            print(
                f"  DAv2 finished in {runtime_sec:.2f} s"
            )

        # -------------------------------------------------------------
        # Load outputs / truth
        # -------------------------------------------------------------

        try:
            depth = load_dav2(depth_path)
            agl = load_agl(agl_path)

            pearson, spearman, valid_pixels = calculate_correlations(
                depth,
                agl,
            )

            total_pixels = int(depth.size)
            valid_pct = (
                100.0 * valid_pixels / total_pixels
                if total_pixels
                else np.nan
            )

            result_row = {
                "tile_id": tile_id,
                "city": city,
                "depth_path": str(depth_path),
                "rgb_path": str(rgb_path),
                "agl_path": str(agl_path),
                "width": int(depth.shape[1]),
                "height": int(depth.shape[0]),
                "valid_pixels": valid_pixels,
                "valid_pct": valid_pct,

                # DAv2 statistics
                "dav2_min": safe_float(np.min(depth)),
                "dav2_max": safe_float(np.max(depth)),
                "dav2_mean": safe_float(np.mean(depth)),
                "dav2_std": safe_float(np.std(depth)),

                # AGL statistics
                "agl_min": safe_float(np.min(agl)),
                "agl_max": safe_float(np.max(agl)),
                "agl_mean": safe_float(np.mean(agl)),
                "agl_std": safe_float(np.std(agl)),

                # Baseline metrics
                "pearson": pearson,
                "spearman": spearman,

                # Performance
                "runtime_sec": safe_float(runtime_sec),

                "status": "ok",
            }

        except Exception as exc:
            print(f"  ERROR: {exc}")

            result_row = {
                "tile_id": tile_id,
                "city": city,
                "depth_path": str(depth_path),
                "rgb_path": str(rgb_path),
                "agl_path": str(agl_path),
                "status": "error",
                "error": str(exc),
            }

        # Replace any older record for the same tile.
        results = [
            r for r in results
            if str(r.get("tile_id")) != tile_id
        ]

        results.append(result_row)

        # Save after EVERY tile so an interruption loses at most one row.
        pd.DataFrame(results).sort_values("tile_id").to_csv(
            METRICS_PATH,
            index=False,
        )

        if result_row["status"] == "ok":
            print(
                f"  Pearson : {result_row['pearson']:.6f}"
            )
            print(
                f"  Spearman: {result_row['spearman']:.6f}"
            )

        print()

    # -----------------------------------------------------------------
    # Final summary
    # -----------------------------------------------------------------

    metrics = pd.read_csv(METRICS_PATH)

    ok = metrics[metrics["status"] == "ok"].copy()

    print("=" * 60)
    print("DFC2019 DAv2 BASELINE COMPLETE")
    print("=" * 60)

    print(f"Total manifest tiles : {len(manifest)}")
    print(f"Successful           : {len(ok)}")
    print(f"Errors               : {len(metrics) - len(ok)}")

    if not ok.empty:
        print("\nPearson:")
        print(
            f"  mean   = {ok['pearson'].mean():.6f}"
        )
        print(
            f"  median = {ok['pearson'].median():.6f}"
        )
        print(
            f"  std    = {ok['pearson'].std():.6f}"
        )

        print("\nSpearman:")
        print(
            f"  mean   = {ok['spearman'].mean():.6f}"
        )
        print(
            f"  median = {ok['spearman'].median():.6f}"
        )
        print(
            f"  std    = {ok['spearman'].std():.6f}"
        )

        print("\nBy city:")

        city_summary = (
            ok.groupby("city")[["pearson", "spearman"]]
            .agg(["mean", "median", "std"])
        )

        print(city_summary)

    print(f"\nMetrics written to:\n{METRICS_PATH}")
    print(f"Depth outputs stored in:\n{DEPTH_DIR}")


if __name__ == "__main__":
    main()
