#!/usr/bin/env python3
"""
DepthWizard2 — Sparse-Anchor RANSAC Mini-Study (v2)

Scientific purpose
------------------
Stage 2 (`evaluate_sparse_anchor_regression.py`) found RANSAC did not
outperform OLS/Huber at n=10/20 grid anchors, using sklearn's default
RANSAC configuration. That result is ambiguous: it could mean

    (a) RANSAC is the wrong tool for this problem (the noise is
        continuous scatter, not a small fraction of gross outliers), or
    (b) RANSAC was starved of data / mistuned (too few anchors for
        consensus-based rejection to be meaningful, default
        residual_threshold heuristic mismatched to this problem's
        noise scale, too few trials).

This script isolates (a) vs (b) by re-running RANSAC, and only RANSAC's
plausible failure modes, under conditions designed to remove the
starvation/mistuning explanation:

1. Anchor counts: 10, 20 (existing Stage-1 grid anchors, reused as-is)
   plus NEW 30, 50, 100 grid anchor sets (generated by re-running the
   unmodified Stage-1 script `evaluate_sparse_anchor_robust.py
   --strategies grid --anchors 30 50 100`, saved to
   sparse_anchor_robust_ext/anchors/ — same deterministic grid
   selection logic, not a new anchor-generation method).

2. residual_threshold is tuned explicitly to this problem's own noise
   scale: a calibration pre-pass fits OLS on the n=20 grid anchors for
   every tile, evaluates residuals (prediction - truth) over each
   tile's strict spatial holdout, pools all tiles' residuals, and uses
   the pooled median absolute residual as a single global
   residual_threshold for every RANSAC fit in the main sweep. This
   replaces sklearn's default (MAD of the target y itself, which is
   not a residual/noise-scale quantity at all for this problem).

3. max_trials raised from 100 (Stage-2 default) to 5000, since small n
   makes unlucky minimal-subset sampling more likely.

4. At every anchor count we report RANSAC's inlier fraction alongside
   MAE/RMSE/Pearson/Spearman, directly next to OLS and Huber fit on the
   SAME anchor sets (same tiles, same coordinates, same eval masks).

Design notes
------------
- Grid placement only (per this study's scope) — Stage 1/2 already
  established grid/random placement comparisons; this study only
  varies anchor count and the RANSAC estimator's own configuration.
- Evaluation is the strict spatial holdout (outside a 16px buffer
  around anchors), matching Stage 1/2's primary comparison.
- Does NOT modify or overwrite sparse_anchor_regression/ (Stage 2) or
  sparse_anchor_robust/ (Stage 1). Anchor generation for n=30/50/100
  is a separate directory (sparse_anchor_robust_ext/); this script's
  own outputs go to sparse_anchor_ransac_v2/.

Outputs
-------
data/dfc2019/experiments/sparse_anchor_ransac_v2/
    config.json
    calibration.json        (pooled OLS residual stats -> chosen threshold)
    results.csv
    summary.csv
    REPORT.txt
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
from scipy.stats import pearsonr, spearmanr
from sklearn.linear_model import HuberRegressor, LinearRegression, RANSACRegressor


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_MANIFEST = PROJECT_ROOT / "data/dfc2019/experiments/dav2_baseline/manifest.csv"
DEFAULT_DEPTH_DIR = PROJECT_ROOT / "data/dfc2019/experiments/dav2_baseline/depth"
DEFAULT_TRUTH_DIR = PROJECT_ROOT / "data/dfc2019/raw/Truth/Track1-Truth"

# n=10/20 grid anchors: exact Stage-1 files.
STAGE1_ANCHOR_DIR = PROJECT_ROOT / "data/dfc2019/experiments/sparse_anchor_robust/anchors"
# n=30/50/100 grid anchors: same generator, new counts (this session).
EXT_ANCHOR_DIR = PROJECT_ROOT / "data/dfc2019/experiments/sparse_anchor_robust_ext/anchors"

DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data/dfc2019/experiments/sparse_anchor_ransac_v2"

ANCHOR_COUNTS = [10, 20, 30, 50, 100]
CALIBRATION_ANCHOR_COUNT = 20
REGRESSORS = ["ols", "huber", "ransac"]

DEFAULT_BUFFER_RADIUS = 16
DEFAULT_MIN_EVAL_PIXELS = 1000
DEFAULT_MAX_TRIALS = 5000

VALID_AGL_EPS = 1e-6


# ============================================================================
# I/O helpers
# ============================================================================

def read_depth(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(path)
    arr = np.load(path, allow_pickle=False)
    if arr.ndim != 2:
        raise ValueError(f"Expected a 2-D depth array, got {arr.shape}: {path}")
    return arr.astype(np.float32, copy=False)


def read_agl(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(path)
    with rasterio.open(path) as src:
        return src.read(1).astype(np.float32, copy=False)


def valid_mask(depth: np.ndarray, agl: np.ndarray) -> np.ndarray:
    return np.isfinite(depth) & np.isfinite(agl) & (agl >= -VALID_AGL_EPS)


def safe_correlations(truth: np.ndarray, prediction: np.ndarray) -> tuple[float, float]:
    if len(truth) < 2:
        return math.nan, math.nan
    if np.allclose(truth, truth[0]) or np.allclose(prediction, prediction[0]):
        return math.nan, math.nan
    return (
        float(pearsonr(truth, prediction).statistic),
        float(spearmanr(truth, prediction).statistic),
    )


def metrics_of(truth: np.ndarray, prediction: np.ndarray) -> dict[str, float]:
    residual = prediction - truth
    p, s = safe_correlations(truth, prediction)
    return {
        "mae_m": float(np.mean(np.abs(residual))),
        "rmse_m": float(np.sqrt(np.mean(residual ** 2))),
        "bias_m": float(np.mean(residual)),
        "pearson": p,
        "spearman": s,
    }


def make_exclusion_mask(shape, rows, cols, radius: int) -> np.ndarray:
    height, width = shape
    result = np.zeros(shape, dtype=bool)
    r = int(radius)
    yy, xx = np.mgrid[-r:r + 1, -r:r + 1]
    disk = (yy * yy + xx * xx) <= r * r
    dy, dx = np.where(disk)
    dy -= r
    dx -= r
    for row, col in zip(rows, cols):
        rr = row + dy
        cc = col + dx
        inside = (rr >= 0) & (rr < height) & (cc >= 0) & (cc < width)
        result[rr[inside], cc[inside]] = True
    return result


# ============================================================================
# Anchor loading
# ============================================================================

def anchor_dir_for_count(anchor_count: int) -> Path:
    return STAGE1_ANCHOR_DIR if anchor_count in (10, 20) else EXT_ANCHOR_DIR


def anchor_file(anchor_count: int, tile_id: str) -> Path:
    return anchor_dir_for_count(anchor_count) / f"{tile_id}_grid_{anchor_count}_00.json"


def load_anchor_set(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Required grid anchor file is missing:\n{path}")

    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    anchors = payload["anchors"]
    if not anchors:
        raise ValueError(f"No anchors in {path}")

    rows = np.asarray([int(a["row"]) for a in anchors], dtype=np.int32)
    cols = np.asarray([int(a["col"]) for a in anchors], dtype=np.int32)
    agl = np.asarray([float(a["agl_m"]) for a in anchors], dtype=np.float64)
    dav2_saved = np.asarray([float(a["dav2"]) for a in anchors], dtype=np.float64)

    if len(np.unique(np.column_stack([rows, cols]), axis=0)) != len(anchors):
        raise ValueError(f"Duplicate anchor coordinates in {path}")
    if not np.all(np.isfinite(agl)) or not np.all(np.isfinite(dav2_saved)):
        raise ValueError(f"Non-finite anchor value(s) in {path}")

    return {"rows": rows, "cols": cols, "agl": agl, "dav2_saved": dav2_saved}


# ============================================================================
# Regressors
# ============================================================================

def build_regressor(name: str, ransac_threshold: float, max_trials: int):
    if name == "ols":
        return LinearRegression()

    if name == "huber":
        return HuberRegressor(epsilon=1.35, alpha=1e-4, max_iter=2000, tol=1e-8)

    if name == "ransac":
        return RANSACRegressor(
            estimator=LinearRegression(),
            min_samples=2,
            residual_threshold=ransac_threshold,
            max_trials=max_trials,
            stop_probability=0.999,
            loss="absolute_error",
            random_state=0,
        )

    raise ValueError(f"Unknown regressor: {name}")


def fit_regression(name: str, depth: np.ndarray, anchor_data: dict, ransac_threshold: float, max_trials: int):
    rows, cols, y = anchor_data["rows"], anchor_data["cols"], anchor_data["agl"]
    x = depth[rows, cols].astype(np.float64)

    if not np.all(np.isfinite(x)):
        raise ValueError("At least one anchor maps to non-finite DAv2.")
    if np.ptp(x) < 1e-10:
        raise ValueError("Anchor DAv2 values have essentially zero range.")

    model = build_regressor(name, ransac_threshold, max_trials)
    model.fit(x.reshape(-1, 1), y)

    if name == "ransac":
        fitted_linear = model.estimator_
        slope = float(np.asarray(fitted_linear.coef_).reshape(-1)[0])
        intercept = float(fitted_linear.intercept_)
    else:
        slope = float(np.asarray(model.coef_).reshape(-1)[0])
        intercept = float(model.intercept_)

    if not np.isfinite(slope) or not np.isfinite(intercept):
        raise ValueError(f"{name} produced non-finite slope/intercept.")

    extra = {"slope_m_per_dav2": slope, "intercept_m": intercept}

    if name == "ransac":
        inlier_mask = model.inlier_mask_
        extra["ransac_inlier_count"] = int(np.count_nonzero(inlier_mask))
        extra["ransac_outlier_count"] = int(len(inlier_mask) - np.count_nonzero(inlier_mask))
        extra["ransac_inlier_fraction"] = float(np.mean(inlier_mask))
        extra["ransac_n_trials"] = int(getattr(model, "n_trials_", -1))

    return model, extra


def evaluate_mask(depth, agl, mask, model):
    use = mask & np.isfinite(depth) & np.isfinite(agl) & (agl >= -VALID_AGL_EPS)
    count = int(np.count_nonzero(use))
    if count < 2:
        return {"mae_m": math.nan, "rmse_m": math.nan, "bias_m": math.nan, "pearson": math.nan, "spearman": math.nan}, count

    x = depth[use].astype(np.float64)
    y = agl[use].astype(np.float64)
    prediction = model.predict(x.reshape(-1, 1)).astype(np.float64)
    return metrics_of(y, prediction), count


# ============================================================================
# Calibration pre-pass: derive residual_threshold from actual OLS fits
# ============================================================================

def calibrate_ransac_threshold(tile_ids, depth_dir, truth_dir, buffer_radius, min_eval_pixels) -> dict:
    """
    Fit OLS on the n=20 grid anchors for every tile, evaluate residuals
    (prediction - truth) over each tile's strict spatial holdout, and pool
    them across all tiles to get this problem's actual noise scale.

    We use the pooled MEDIAN ABSOLUTE RESIDUAL as the RANSAC
    residual_threshold: this is the direct analogue of sklearn's own
    MAD-style heuristic, but computed from real model residuals against
    ground truth rather than from the raw spread of the target values.
    """
    pooled_abs_residuals = []
    per_tile = []

    for tile_id in tile_ids:
        depth_path = depth_dir / f"{tile_id}_depth.npy"
        truth_path = truth_dir / f"{tile_id}_AGL.tif"

        depth = read_depth(depth_path)
        agl = read_agl(truth_path)
        valid = valid_mask(depth, agl)

        a_path = anchor_file(CALIBRATION_ANCHOR_COUNT, tile_id)
        anchor_data = load_anchor_set(a_path)
        rows, cols = anchor_data["rows"], anchor_data["cols"]

        model, _ = fit_regression("ols", depth, anchor_data, ransac_threshold=1.0, max_trials=1)

        anchor_mask = np.zeros(valid.shape, dtype=bool)
        anchor_mask[rows, cols] = True
        exclusion = make_exclusion_mask(valid.shape, rows, cols, buffer_radius)
        strict_mask = valid & ~exclusion

        use = strict_mask & np.isfinite(depth) & np.isfinite(agl) & (agl >= -VALID_AGL_EPS)
        if int(np.count_nonzero(use)) < min_eval_pixels:
            continue

        x = depth[use].astype(np.float64)
        y = agl[use].astype(np.float64)
        prediction = model.predict(x.reshape(-1, 1))
        abs_residual = np.abs(prediction - y)

        pooled_abs_residuals.append(abs_residual)
        per_tile.append(float(np.median(abs_residual)))

    pooled = np.concatenate(pooled_abs_residuals)

    return {
        "n_tiles": len(per_tile),
        "n_pixels_pooled": int(pooled.size),
        "pooled_median_abs_residual_m": float(np.median(pooled)),
        "pooled_mean_abs_residual_m": float(np.mean(pooled)),
        "pooled_p25_abs_residual_m": float(np.percentile(pooled, 25)),
        "pooled_p75_abs_residual_m": float(np.percentile(pooled, 75)),
        "per_tile_median_abs_residual_m": per_tile,
        "chosen_residual_threshold_m": float(np.median(pooled)),
        "method": (
            "Pooled median absolute residual of OLS fit on n=20 grid "
            "anchors, evaluated on each tile's strict spatial holdout, "
            "across all tiles. Replaces sklearn's default residual_threshold "
            "(MAD of target y) with an actual model-residual noise scale."
        ),
    }


# ============================================================================
# One run
# ============================================================================

def run_one(tile_id, truth_path, depth_path, anchor_count, regressor_name,
            ransac_threshold, max_trials, buffer_radius, min_eval_pixels) -> dict:

    depth = read_depth(depth_path)
    agl = read_agl(truth_path)

    if depth.shape != agl.shape:
        raise ValueError(f"{tile_id}: DAv2/AGL shape mismatch: {depth.shape} vs {agl.shape}")

    valid = valid_mask(depth, agl)

    a_path = anchor_file(anchor_count, tile_id)
    anchor_data = load_anchor_set(a_path)
    rows, cols = anchor_data["rows"], anchor_data["cols"]

    if len(rows) != anchor_count:
        raise ValueError(f"{a_path}: expected {anchor_count} anchors, found {len(rows)}")
    if not np.all(valid[rows, cols]):
        raise ValueError(f"{tile_id}: grid anchor contains invalid metric pixel(s).")

    dav2_current = depth[rows, cols].astype(np.float64)
    if not np.allclose(anchor_data["dav2_saved"], dav2_current, rtol=1e-6, atol=1e-6):
        max_diff = float(np.max(np.abs(anchor_data["dav2_saved"] - dav2_current)))
        raise ValueError(f"{tile_id}: anchor DAv2 values do not match current depth file. Max diff={max_diff}")

    model, fit_info = fit_regression(regressor_name, depth, anchor_data, ransac_threshold, max_trials)

    anchor_mask = np.zeros(valid.shape, dtype=bool)
    anchor_mask[rows, cols] = True
    all_mask = valid & ~anchor_mask
    all_metrics, all_count = evaluate_mask(depth, agl, all_mask, model)

    exclusion = make_exclusion_mask(valid.shape, rows, cols, buffer_radius)
    strict_mask = valid & ~exclusion
    strict_metrics, strict_count = evaluate_mask(depth, agl, strict_mask, model)

    if all_count < min_eval_pixels or strict_count < min_eval_pixels:
        raise ValueError(f"{tile_id}: insufficient evaluation pixels (all={all_count}, strict={strict_count}).")

    region = "JAX" if tile_id.startswith("JAX_") else "OMA" if tile_id.startswith("OMA_") else "UNKNOWN"

    result = {
        "tile_id": tile_id,
        "region": region,
        "placement": "grid",
        "anchor_count": anchor_count,
        "regressor": regressor_name,
        "eval_pixels_all": all_count,
        "eval_pixels_strict": strict_count,
        **fit_info,
    }

    for key, value in all_metrics.items():
        result[f"all_{key}"] = value
    for key, value in strict_metrics.items():
        result[f"strict_{key}"] = value

    return result


# ============================================================================
# Summary
# ============================================================================

METRICS = ["strict_mae_m", "strict_rmse_m", "strict_bias_m", "strict_pearson", "strict_spearman"]


def create_summary(results: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for (regressor, anchor_count), group in results.groupby(["regressor", "anchor_count"], sort=True):
        row = {
            "regressor": regressor,
            "anchor_count": int(anchor_count),
            "tiles": group["tile_id"].nunique(),
        }
        for metric in METRICS:
            values = pd.to_numeric(group[metric], errors="coerce").dropna()
            if len(values):
                row[f"{metric}_mean"] = float(values.mean())
                row[f"{metric}_median"] = float(values.median())
        row["pearson_lt_0"] = int((group["strict_pearson"] < 0).sum())
        row["rmse_gt_10m"] = int((group["strict_rmse_m"] > 10).sum())

        if "ransac_inlier_fraction" in group:
            vals = pd.to_numeric(group["ransac_inlier_fraction"], errors="coerce").dropna()
            if len(vals):
                row["ransac_inlier_fraction_mean"] = float(vals.mean())
                row["ransac_inlier_fraction_median"] = float(vals.median())

        rows.append(row)

    return pd.DataFrame(rows).sort_values(["anchor_count", "regressor"]).reset_index(drop=True)


# ============================================================================
# Main
# ============================================================================

def parse_args():
    parser = argparse.ArgumentParser(description="RANSAC starvation-vs-mismatch mini-study.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--depth-dir", type=Path, default=DEFAULT_DEPTH_DIR)
    parser.add_argument("--truth-dir", type=Path, default=DEFAULT_TRUTH_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--anchors", type=int, nargs="+", default=ANCHOR_COUNTS)
    parser.add_argument("--buffer-radius", type=int, default=DEFAULT_BUFFER_RADIUS)
    parser.add_argument("--min-eval-pixels", type=int, default=DEFAULT_MIN_EVAL_PIXELS)
    parser.add_argument("--max-trials", type=int, default=DEFAULT_MAX_TRIALS)
    parser.add_argument("--tiles", nargs="*", default=None)
    parser.add_argument("--limit", type=int, default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = pd.read_csv(args.manifest.resolve())
    tile_ids = manifest["tile_id"].astype(str).tolist()

    if args.tiles:
        requested = set(args.tiles)
        tile_ids = [t for t in tile_ids if t in requested]

    if args.limit is not None:
        tile_ids = tile_ids[: args.limit]

    depth_dir = args.depth_dir.resolve()
    truth_dir = args.truth_dir.resolve()

    print("=" * 78)
    print("DepthWizard2 — Sparse-Anchor RANSAC Mini-Study (v2)")
    print("=" * 78)
    print(f"Tiles:      {len(tile_ids)}")
    print(f"Counts:     {args.anchors}")
    print(f"Regressors: {REGRESSORS}")
    print(f"Max trials: {args.max_trials}")
    print()
    print("Calibrating RANSAC residual_threshold from actual OLS fits "
          f"(n={CALIBRATION_ANCHOR_COUNT} grid anchors)...")

    calibration = calibrate_ransac_threshold(
        tile_ids, depth_dir, truth_dir, args.buffer_radius, args.min_eval_pixels
    )

    threshold = calibration["chosen_residual_threshold_m"]

    print(
        f"  pooled median |residual| = {calibration['pooled_median_abs_residual_m']:.4f} m "
        f"(n_tiles={calibration['n_tiles']}, n_pixels={calibration['n_pixels_pooled']:,})"
    )
    print(f"  -> RANSAC residual_threshold fixed at {threshold:.4f} m for the whole sweep")
    print("=" * 78)
    print()

    (output_dir / "calibration.json").write_text(json.dumps(calibration, indent=2), encoding="utf-8")

    config = {
        "experiment": "sparse_anchor_ransac_v2",
        "scientific_question": (
            "Was RANSAC's earlier (Stage-2) underperformance a structural "
            "mismatch to this problem's noise, or was it starved of data / "
            "mistuned?"
        ),
        "placement": "grid",
        "anchor_counts": args.anchors,
        "regressors": REGRESSORS,
        "ransac_residual_threshold_m": threshold,
        "ransac_residual_threshold_source": "empirical (pooled OLS residuals), not sklearn default",
        "ransac_max_trials": args.max_trials,
        "tiles": tile_ids,
        "buffer_radius_px": args.buffer_radius,
    }
    (output_dir / "config.json").write_text(json.dumps(config, indent=2), encoding="utf-8")

    jobs = [
        (tile_id, anchor_count, regressor)
        for anchor_count in args.anchors
        for tile_id in tile_ids
        for regressor in REGRESSORS
    ]

    results = []
    total = len(jobs)

    for index, (tile_id, anchor_count, regressor) in enumerate(jobs, start=1):
        truth_path = truth_dir / f"{tile_id}_AGL.tif"
        depth_path = depth_dir / f"{tile_id}_depth.npy"

        print(f"{index:5d}/{total} {tile_id:14s} n={anchor_count:3d} {regressor:7s} ...", end=" ", flush=True)

        try:
            row = run_one(
                tile_id=tile_id,
                truth_path=truth_path,
                depth_path=depth_path,
                anchor_count=anchor_count,
                regressor_name=regressor,
                ransac_threshold=threshold,
                max_trials=args.max_trials,
                buffer_radius=args.buffer_radius,
                min_eval_pixels=args.min_eval_pixels,
            )
            results.append(row)
            extra = ""
            if regressor == "ransac":
                extra = f" inliers={row['ransac_inlier_fraction']:.2f}"
            print(f"strict MAE={row['strict_mae_m']:.3f}m RMSE={row['strict_rmse_m']:.3f}m P={row['strict_pearson']:.4f}{extra}")
        except Exception as exc:
            print("FAILED")
            raise RuntimeError(
                f"Run failed: tile={tile_id} n={anchor_count} regressor={regressor} error={exc}"
            ) from exc

    results_df = pd.DataFrame(results).sort_values(["anchor_count", "regressor", "tile_id"]).reset_index(drop=True)
    results_path = output_dir / "results.csv"
    results_df.to_csv(results_path, index=False)

    summary_df = create_summary(results_df)
    summary_path = output_dir / "summary.csv"
    summary_df.to_csv(summary_path, index=False)

    report_lines = [
        "DepthWizard2 — Sparse-Anchor RANSAC Mini-Study (v2)",
        "=" * 68,
        "",
        "Question: was RANSAC's earlier underperformance a structural",
        "mismatch (continuous noise) or starvation/mistuning (too few",
        "anchors, wrong residual_threshold, too few trials)?",
        "",
        f"RANSAC residual_threshold = {threshold:.4f} m "
        "(empirical, from pooled OLS residuals — not sklearn default)",
        f"RANSAC max_trials = {args.max_trials}",
        "Placement: grid only. Anchor counts: " + ", ".join(str(n) for n in args.anchors),
        "",
        summary_df.to_string(index=False),
        "",
        "FILES",
        f"results.csv:      {results_path}",
        f"summary.csv:      {summary_path}",
        f"calibration.json: {output_dir / 'calibration.json'}",
    ]

    (output_dir / "REPORT.txt").write_text("\n".join(report_lines), encoding="utf-8")

    print()
    print("=" * 78)
    print("COMPLETE")
    print("=" * 78)
    print(summary_df.to_string(index=False))
    print()
    print(f"Results:  {results_path}")
    print(f"Summary:  {summary_path}")
    print(f"Report:   {output_dir / 'REPORT.txt'}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        raise SystemExit(130)
